-- MySQL Script generated by MySQL Workbench
-- Tue Oct 22 11:55:07 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sales
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sales
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sales` DEFAULT CHARACTER SET utf8 ;
USE `sales` ;

-- -----------------------------------------------------
-- Table `sales`.`salesman`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sales`.`salesman` (
  `salesman_id` DECIMAL(5) NOT NULL,
  `name` VARCHAR(30) NULL,
  `city` VARCHAR(15) NULL,
  `comision` DECIMAL(5,2) NULL,
  PRIMARY KEY (`salesman_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sales`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sales`.`customer` (
  `customer_id` DECIMAL(5) NOT NULL,
  `name` VARCHAR(30) NULL,
  `city` VARCHAR(15) NULL,
  `grade` DECIMAL(3) NULL,
  PRIMARY KEY (`customer_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sales`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sales`.`orders` (
  `order_id` DECIMAL(5) NOT NULL,
  `purch_amt` DECIMAL(8,2) NULL,
  `order_date` DATE NULL,
  `customer_id` DECIMAL(5) NULL,
  `salesman_id` DECIMAL(5) NULL,
  `customer_customer_id` DECIMAL(5) NOT NULL,
  `salesman_salesman_id` DECIMAL(5) NOT NULL,
  PRIMARY KEY (`order_id`, `customer_customer_id`, `salesman_salesman_id`),
  INDEX `fk_orders_customer1_idx` (`customer_customer_id` ASC) VISIBLE,
  INDEX `fk_orders_salesman1_idx` (`salesman_salesman_id` ASC) VISIBLE,
  CONSTRAINT `fk_orders_customer1`
    FOREIGN KEY (`customer_customer_id`)
    REFERENCES `sales`.`customer` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_salesman1`
    FOREIGN KEY (`salesman_salesman_id`)
    REFERENCES `sales`.`salesman` (`salesman_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
